from pathlib import Path

path = Path('index.html')
text = path.read_text()
old = "      const parameters = [\n        'temp_ext','temp_int','temp_mix','temp_coil','temp_hx','temp6',\n        'fan_supply_out','fan_extract_out','fan_supply_tach','fan_extract_tach',\n        'damper_supply','damper_extract','damper_current_supply','damper_current_extract',\n        'cool_setpoint','heat_setpoint','fan_setpoint','airflow_demand','pressure_demand',\n        'system_status','fault_code'\n      ];\n\n      const monitorDefaults = ['temp_ext','temp_int','fan_supply_out','fan_extract_out','damper_supply','cool_setpoint'];\n"
new = "      const parameters = [\n        { id: 'temp_ext', label: 'Temp Ext' },\n        { id: 'temp_int', label: 'Temp Int' },\n        { id: 'temp_mix', label: 'Temp Mix' },\n        { id: 'temp_coil', label: 'Temp Coil' },\n        { id: 'temp_hx', label: 'Temp HX' },\n        { id: 'temp6', label: 'Temp 6' },\n        { id: 'fan_supply_out', label: 'Fan Supply Out' },\n        { id: 'fan_extract_out', label: 'Fan Extract Out' },\n        { id: 'fan_supply_tach', label: 'Fan Supply Tach' },\n        { id: 'fan_extract_tach', label: 'Fan Extract Tach' },\n        { id: 'damper_supply', label: 'Damper Supply' },\n        { id: 'damper_extract', label: 'Damper Extract' },\n        { id: 'damper_current_supply', label: 'Damper Current Supply' },\n        { id: 'damper_current_extract', label: 'Damper Current Extract' },\n        { id: 'cool_setpoint', label: 'Cool Setpoint' },\n        { id: 'heat_setpoint', label: 'Heat Setpoint' },\n        { id: 'fan_setpoint', label: 'Fan Setpoint' },\n        { id: 'airflow_demand', label: 'Airflow Demand' },\n        { id: 'pressure_demand', label: 'Pressure Demand' },\n        { id: 'system_status', label: 'System Status' },\n        { id: 'fault_code', label: 'Fault Code' },\n        { id: 'control_mode', label: 'Control Mode' }\n      ];\n\n      const parameterMap = new Map(parameters.map(item => [item.id, item.label]));\n      const labelMap = new Map(parameters.map(item => [item.label, item.id]));\n      const parameterLabel = id => parameterMap.has(id) ? parameterMap.get(id) : id;\n      const parameterIdFromLabel = label => labelMap.get(label);\n\n      const monitorDefaults = ['temp_ext','temp_int','fan_supply_out','fan_extract_out','damper_supply','cool_setpoint'];\n"
if old not in text:
    raise SystemExit('old block missing')
text = text.replace(old, new)
path.write_text(text, encoding='utf-8')
